service: video-view-worker

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: ${env:AWS_REGION}
  stage: ${opt:stage, 'dev'}
  stackName: ${self:service}-${opt:stage, 'dev'}
  timeout: 20
  logRetentionInDays: 7
  tracing:
    lambda: true
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    NODE_OPTIONS: --enable-source-maps

functions:
  consumeWatchEvents:
    handler: src/handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:watch-events
          batchSize: 1

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - .git/**
    - .vscode/**
    - node_modules/.cache/**
