service: analytics-worker

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  consumeWatchEvents:
    handler: src/handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:sa-east-1:${env:AWS_ACCOUNT_ID}:watch-events

package:
  individually: true