services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: sportsrats-postgres
    volumes:
      - db:/bitnami/postgresql
    environment:
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - sportsrats-network

networks:
  sportsrats-network:
    driver: bridge

volumes:
  db:
