service: api-gateway

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: ${env:AWS_REGION}
  stage: ${opt:stage, 'dev'}
  stackName: ${self:service}-${opt:stage, 'dev'}
  timeout: 20
  logRetentionInDays: 7
  tracing:
    lambda: true
  environment:
    NODE_ENV: ${env:NODE_ENV}
    JWT_SECRET: ${env:JWT_SECRET}
    ORIGIN_URL: ${env:ORIGIN_URL}
    AWS_REGION: ${env:AWS_REGION}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    SQS_QUEUE_URL: ${env:SQS_QUEUE_URL}
    DATABASE_URL: ${env:DATABASE_URL}
    NODE_OPTIONS: --enable-source-maps
  httpApi:
    cors:
      allowedOrigins:
        - ${env:ORIGIN_URL}
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: true

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi: '*'

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - .git/**
    - .vscode/**
    - node_modules/.cache/**
